version: '3.8'

services:
  # DocumentAgent Web Application
  documentagent:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./document_vector_db:/app/document_vector_db
      - ./templates:/app/templates
    environment:
      - FLASK_APP=web_app.py
      - FLASK_ENV=production
      - VECTOR_DB_PATH=/app/document_vector_db
      - UPLOAD_FOLDER=/app/uploads
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - documentagent-network

  # Ollama LLM Service
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - documentagent-network
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - documentagent
    restart: unless-stopped
    networks:
      - documentagent-network
    profiles:
      - production

volumes:
  ollama_data:

networks:
  documentagent-network:
    driver: bridge
